 
"use client";

import { motion, useInView } from "framer-motion";
import { useRef, useState, useEffect } from "react";
import { Button } from "@/components/common/button";
import { Input } from "@/components/common/input";
import { Textarea } from "@/components/common/textarea";
import { X, PhoneCall, LucideIcon } from "lucide-react";
import { useContactForm } from "@/hooks/useContactForm";
import React from "react";
import {
  Phone,
  Mail,
  Clock,
  MapPin
} from "lucide-react";

// ICON MAP (string → lucide component)
const icons: Record<string, LucideIcon> = {
  Phone,
  Mail,
  Clock,
  MapPin,
};
type ContactPayload = {
  fullName: string;
  phone: string;
  heardAboutUs: string;
  message: string;
  email?: string;
  businessName?: string;
};


const hearAboutOptions = [
  "Google Search",
  "Social Media (Instagram / Facebook / LinkedIn / Twitter)",
  "YouTube",
  "Email Newsletter",
  "Friends / Family (Word of Mouth)",
  "Existing Customer / Referral",
  "Online Ads (Google Ads, Facebook Ads, etc.)",
  "Website / Blog",
  "Event / Seminar / Conference",
  "Other",
];

export function ContactForm({ getContact = [] }) {
  const [contactInfo, setContactInfo] = useState<ContactInfoItem[]>([]);
  const ref = useRef<HTMLElement | null>(null);
  const isInView = useInView(ref, { once: true, amount: 0.2 });
  const { mutateAsync, isPending } = useContactForm();

  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    business: "",
    message: "",
    hearAbout: "",
    hearAboutOther: "",
  });

  const [showAlert, setShowAlert] = useState(false);
  const [phoneError, setPhoneError] = useState("");
  const [emailError, setEmailError] = useState("");
  const [nameError, setNameError] = useState("");
  const [hearAboutOtherError, setHearAboutOtherError] = useState("");
  const [isMessageAutoGenerated, setIsMessageAutoGenerated] = useState(false);
  const [submitError, setSubmitError] = useState("");

  // ✅ Fetch contact data from public folder
  useEffect(() => {
    const fetchContactData = async () => {
      try {
        const response = await fetch("/contact.json");
        if (!response.ok) throw new Error("Failed to load contact data");

        const data = await response.json();
        setContactInfo(data.contactInfo || []);
      } catch (err) {
        console.error("Error loading contact data:", err);
      }
    };

    fetchContactData();
  }, []);

  // Get specific contact info by title
  const getContactInfo = (title: string) => {
    return contactInfo.find((item) => item.title === title);
  };

  const isValidEmail = (email: string) =>
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  const isValidName = (name: string) =>
    /^[a-zA-Z\s]+$/.test(name) && name.trim().length > 0;

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    const { name, value } = e.target;

    if (name === "name") {
      if (!/^[a-zA-Z\s]*$/.test(value)) return;
      setNameError("");
    }
    if (name === "email") setEmailError("");
    if (name === "phone") {
      if (!/^\d*$/.test(value)) return;
      if (value.length > 10) return;
      setPhoneError("");
    }
    if (name === "business" && !/^[a-zA-Z0-9\s&.,'-]*$/.test(value)) return;
    if (name === "hearAboutOther") setHearAboutOtherError("");
    if (name === "message" && isMessageAutoGenerated)
      setIsMessageAutoGenerated(false);

    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setSubmitError(""); // Clear any previous errors

    let hasError = false;

    // Validation
    if (!formData.name.trim()) {
      setNameError("Name is required");
      hasError = true;
    } else if (!isValidName(formData.name)) {
      setNameError("Please enter a valid name (letters only)");
      hasError = true;
    }

    if (!formData.phone.trim()) {
      setPhoneError("Phone number is required");
      hasError = true;
    } else if (formData.phone.length !== 10) {
      setPhoneError("Phone number must be exactly 10 digits");
      hasError = true;
    }

    if (formData.email && !isValidEmail(formData.email)) {
      setEmailError("Please enter a valid email address");
      hasError = true;
    }

    if (!formData.hearAbout) {
      hasError = true;
    }

    if (formData.hearAbout === "Other" && !formData.hearAboutOther.trim()) {
      setHearAboutOtherError("Please specify how you heard about us");
      hasError = true;
    }

    if (!formData.message.trim()) {
      hasError = true;
    }

    if (hasError) return;

    try {
      // 🔥 SEND CONTACT DATA TO DATABASE
      const payload: ContactPayload = {
        fullName: formData.name.trim(),
        phone: formData.phone.trim(),
        heardAboutUs:
          formData.hearAbout === "Other"
            ? formData.hearAboutOther.trim()
            : formData.hearAbout,
        message: formData.message.trim(),
      };

      // Only add email if provided
      if (formData.email.trim()) {
        payload.email = formData.email.trim();
      }

      // Only add business name if provided
      if (formData.business.trim()) {
        payload.businessName = formData.business.trim();
      }

      console.log("Submitting payload:", payload);
      
      const result = await mutateAsync(payload);
      console.log("Submission successful:", result);

      // Show success alert
      setShowAlert(true);

      // RESET FORM
      setFormData({
        name: "",
        email: "",
        phone: "",
        business: "",
        message: "",
        hearAbout: "",
        hearAboutOther: "",
      });
    } catch (error: unknown) {
  console.error("Form submission error:", error);

  let errorMessage = "Failed to submit form. Please try again.";

  if (error && typeof error === "object" && "message" in error) {
    errorMessage = (error as { message: string }).message;
  } else if (typeof error === "string") {
    errorMessage = error;
  }

  setSubmitError(errorMessage);
}
  };

  const inputBaseClasses =
    "w-full text-base border-gray-200 bg-green-50/70 rounded-lg h-11 transition-all duration-300 p-2.5 text-gray placeholder:text-black";

  const focusClasses =
    "focus:border-green-400 focus:ring-2 focus:ring-green-100 focus:outline-none";

  const textareaBaseClasses =
    "w-full text-base min-h-[120px] border-gray-200 bg-green-50/70 rounded-lg resize-none transition-all duration-300 p-2.5 text-black placeholder:text-black";

  return (
    <section
      id="contact-us"
      ref={ref}
      className="py-8 sm:py-12 lg:py-16 xl:py-20 px-3 sm:px-4 lg:px-6 xl:px-20 bg-white relative"
    >
      <div className="max-w-7xl mx-auto text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[rgb(6_182_212_/_0.1)] border border-[rgb(6_182_212_/_0.2)] backdrop-blur-sm mb-6">
          <PhoneCall className="w-4 h-4 text-cyan-600" />
          <span className="text-sm font-medium text-slate-700">Contact Us</span>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl lg:text-5xl font-bold mb-3">
            <span className="text-slate-900">Our </span>
            <span className="bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">
              Get Started Today
            </span>
          </h2>

          <p className="text-lg text-slate-600">
            Ready to transform your Business? Contact us for a free demo and
            consultation.
          </p>
        </motion.div>

        {showAlert && (
          <div className="fixed inset-0 flex items-center justify-center bg-black/50 z-50 p-3 sm:p-4">
            <div className="bg-white rounded-xl shadow-lg max-w-sm sm:max-w-md w-full p-4 sm:p-6 relative text-center mx-4">
              <button
                onClick={() => setShowAlert(false)}
                className="absolute top-2 right-2 sm:top-3 sm:right-3 text-gray-400 hover:text-gray-600 bg-transparent border-0 cursor-pointer p-1"
                type="button"
              >
                <X className="w-4 h-4 sm:w-5 sm:h-5" />
              </button>
              <h3 className="text-lg sm:text-xl font-bold text-primary mb-2 sm:mb-3">
                Informational Message
              </h3>
              <p className="text-sm sm:text-base text-gray-700">
                Thank you for your interest! We will contact you soon. <br />
                For further inquiry contact us on{" "}
                <span className="font-semibold text-primary">8149798679</span>.
              </p>
              <button
                onClick={() => setShowAlert(false)}
                className="mt-4 sm:mt-6 bg-gradient-to-r from-primary to-primary-dark text-white px-4 sm:px-6 py-2 text-sm sm:text-base rounded-full cursor-pointer border-0"
                type="button"
              >
                OK
              </button>
            </div>
          </div>
        )}

        <div className="flex flex-col lg:flex-row gap-6 sm:gap-8 lg:gap-12 items-start">
          {/* LEFT FORM */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="w-full lg:w-1/2 order-2 lg:order-1"
          >
            <div className="bg-primary/5 border border-primary/20 rounded-xl sm:rounded-2xl p-4 sm:p-6 lg:p-8 shadow-lg">
              <h3 className="text-lg sm:text-xl lg:text-2xl font-bold text-gray-900 mb-4 sm:mb-6 text-left">
                Send us a Message
              </h3>

              {submitError && (
                <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
                  <p className="text-red-600 text-sm">{submitError}</p>
                </div>
              )}

              <form
                onSubmit={handleSubmit}
                className="space-y-4 sm:space-y-5 lg:space-y-6"
              >
                {/* Name & Email */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Full Name *
                    </label>

                    <Input
                      name="name"
                      value={formData.name}
                      onChange={handleChange}
                      required
                      className={`${inputBaseClasses} text-gray-900 placeholder-gray-500 ${focusClasses} ${
                        nameError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter your full name"
                    />

                    {nameError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {nameError}
                      </p>
                    )}
                  </div>

                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Email Address
                    </label>

                    <Input
                      name="email"
                      type="email"
                      value={formData.email}
                      onChange={handleChange}
                      className={`${inputBaseClasses} text-gray-900 placeholder-gray-500 ${focusClasses} ${
                        emailError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter your email"
                    />

                    {emailError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {emailError}
                      </p>
                    )}
                  </div>
                </div>

                {/* Phone & Business */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Phone Number *
                    </label>

                    <Input
                      name="phone"
                      type="tel"
                      value={formData.phone}
                      onChange={handleChange}
                      required
                      className={`${inputBaseClasses} text-gray-900 placeholder-gray-500 ${focusClasses} ${
                        phoneError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter your phone number"
                    />

                    {phoneError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {phoneError}
                      </p>
                    )}
                  </div>

                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Business Name
                    </label>

                    <Input
                      name="business"
                      value={formData.business}
                      onChange={handleChange}
                      className={`${inputBaseClasses} text-gray-900 placeholder-gray-500 ${focusClasses}`}
                      placeholder="Enter your business name"
                    />
                  </div>
                </div>

                {/* Hear About */}
                <div className="relative">
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                    Where did you hear about us? *
                  </label>

                  <select
                    name="hearAbout"
                    value={formData.hearAbout}
                    onChange={handleChange}
                    required
                    className="
                      w-full text-xs sm:text-sm
                      border border-gray-200 rounded-lg h-11
                      transition-all duration-300 p-2 sm:p-2.5
                      bg-green-50/70 text-black appearance-none
                      focus:border-green-400 focus:ring-2 focus:ring-green-100 focus:outline-none
                    "
                  >
                    <option value="" hidden>
                      Select an option
                    </option>

                    {hearAboutOptions.map((option, idx) => (
                      <option key={idx} value={option}>
                        {option}
                      </option>
                    ))}
                  </select>

                  <svg
                    className="pointer-events-none absolute right-3 top-[calc(50%+0.75rem)] -translate-y-1/2 h-4 w-4 text-gray-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M5.23 7.21a.75.75 0 011.06.02L10 10.94l3.71-3.71a.75.75 0 111.06 1.06l-4.25 4.25a.75.75 0 01-1.06 0L5.21 8.27a.75.75 0 01.02-1.06z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>

                {formData.hearAbout === "Other" && (
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                      Other (please mention) *
                    </label>

                    <Input
                      name="hearAboutOther"
                      value={formData.hearAboutOther}
                      onChange={handleChange}
                      required
                      className={`${inputBaseClasses} ${focusClasses} ${
                        hearAboutOtherError ? "border-red-500" : ""
                      }`}
                      placeholder="Enter details..."
                    />

                    {hearAboutOtherError && (
                      <p className="text-red-500 text-xs sm:text-sm mt-1">
                        {hearAboutOtherError}
                      </p>
                    )}
                  </div>
                )}

                {/* Message */}
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1 sm:mb-2 text-left">
                    Message *
                  </label>

                  <Textarea
                    name="message"
                    value={formData.message}
                    onChange={handleChange}
                    required
                    className={`${textareaBaseClasses} ${focusClasses}`}
                    placeholder="Tell us about your requirements..."
                  />
                </div>

                <button
                  type="submit"
                  disabled={isPending}
                  className="w-full bg-gradient-to-r from-blue-600 to-emerald-500 hover:from-blue-700 hover:to-emerald-600 text-white py-2.5 sm:py-3 text-base sm:text-lg font-semibold rounded-lg shadow-lg transition-all duration-300 cursor-pointer border-0 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isPending ? "Sending..." : "Send Message"}
                </button>
              </form>
            </div>
          </motion.div>

          {/* RIGHT SECTION */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="w-full lg:w-1/2 order-1 lg:order-2"
          >
            <div className="space-y-3 sm:space-y-4 lg:space-y-5">
              <div className="text-center">
                <h4 className="text-lg sm:text-xl font-bold text-gray-900 mb-2">
                  Contact Information
                </h4>
              </div>

              {/* Top 3: Phone, Email, Support Hours */}
              <div className="grid grid-cols-3 gap-3 sm:gap-4">
                {contactInfo
                  .filter((item) =>
                    ["Phone", "Email", "Support Hours"].includes(item.title)
                  )
                  .map((item) => {
                    const Icon = icons[item.icon];

                    return (
                      <div
                        key={item.id}
                        className="flex flex-col items-center text-center"
                      >
                        <div className="p-2 rounded-full bg-primary-light flex items-center justify-center mb-1">
                          <Icon className="h-4 w-4" />
                        </div>

                        <h5 className="font-semibold text-gray-900 text-xs mb-1">
                          {item.title}
                        </h5>

                        <p className="text-gray-600 text-[11px] leading-tight break-words">
                          {item.details1}
                        </p>

                        {item.details2 && (
                          <p className="text-[10px] text-gray-500 mt-1 break-words">
                            {item.details2}
                          </p>
                        )}
                      </div>
                    );
                  })}
              </div>

              {/* Office Section */}
              <div className="bg-primary-light rounded-lg p-3 shadow-sm mt-4">
                {contactInfo
                  .filter((item) => item.title === "Office")
                  .map((item) => {
                    const Icon = icons[item.icon];
                    const offices = Array.isArray(item.details1)
                      ? item.details1
                      : [];

                    return (
                      <div key={item.id}>
                        <div className="flex items-center justify-center mb-2">
                          <Icon className="h-4 w-4 mr-1" />
                          <h5 className="font-semibold text-gray-900 text-sm">
                            Office Locations
                          </h5>
                        </div>

                        <div className="grid gap-2">
                          {offices.map((address: string, idx: number) => (
                            <div
                              key={idx}
                              className="bg-white rounded p-2 border-l-4 border-primary"
                            >
                              <div className="flex items-start">
                                <span className="inline-flex items-center justify-center w-4 h-4 bg-primary text-white rounded-full text-[10px] font-semibold mr-2 mt-0.5 flex-shrink-0">
                                  {idx + 1}
                                </span>
                                <p className="text-gray-700 text-xs leading-tight break-words">
                                  {address}
                                </p>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    );
                  })}
              </div>

              {/* MAP */}
              <div className="bg-primary-light rounded-lg overflow-hidden shadow-md">
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15036.51761826522!2d74.18727!3d19.57895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b887760ab19f%3A0x3fd52e46fe6d323f!2sSoulSoft%20Infotech!5e0!3m2!1sen!2sin!4v1758356538198!5m2!1sen!2sin"
                  width="100%"
                  height="260"
                  style={{ border: 0 }}
                  allowFullScreen
                  loading="lazy"
                  referrerPolicy="no-referrer-when-downgrade"
                  className="rounded-lg"
                  title="SoulSoft Infotech Office Location"
                ></iframe>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}